#version: 3.8
#
#services:
#  app:
#	image: app
#	ports:
# 	-	8183:8182
#	environments:
#	  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/myuser
#	  SPRING_DATASOURCE_USERNAME: root
#	  SPRING_DATASOURCE_PASSWORD: root
#	  SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
#	  SPRING_JPA_HIBERNATE_DDL-AUTO : update
#	  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
#	  
#	depends_on:
#  	- db
#  
#
#	db:
#		image: mysql8
#		environments:
#		  DATABASE_HOST: mysql8
#		  DATABASE_PORT: 3306
#		  MYSQL_USER: root
#		  MYSQL_ROOT_PASSWORD: root
#		  MYSQL_DATABASE: myuser	  	